### ISSUE TITLE
Export STL as ASCII?

### ISSUE THREAD

**Issue by DScrimpsher** [aconz2/Fusion360Exporter#11]
This is a great script. 
Would it be possible to export the STL files as ASCII instead of binary?

Thank you.

**Comment by aconz2** [comment]
That is not an option I see from fusion [ifself](http://help.autodesk.com/view/fusion360/ENU/?guid=GUID-87489be2-dca3-4ca8-9c18-b78c7dd8686d). I think you would be better off using a conversion tool. I'm not aware of any but if I had to do this I would probably use the trimesh library; looks like they have an export STL ASCII [here](https://trimsh.org/trimesh.exchange.stl.html#trimesh.exchange.stl.export_stl_ascii)

**Comment by DScrimpsher** [comment]
Thank you for the response. I will look at those links.
