### ISSUE TITLE
Add feature to export all versions of each file

### ISSUE THREAD

**Issue by ACEngi** [aconz2/Fusion360Exporter#12]
Thank you for making this script available to all of us. I have used your Fusion360Expoter several times. It appears to work flawlessly. For me it is limited as it only exports the most recent version of any file. It would be MOST helpful if the script could be expanded with a feature, (selectable), to export all of the versions for individual files. If you are interested in visiting this script again, perhaps folders within projects could be selected for export. This would allow someone to export more selectively.

**Comment by aconz2** [comment]
I'll see what I can do. I think an option for `n`-latest versions or `*` for all versions would be good

**Comment by ACEngi** [comment]
Hi Andrew,

I'm so pleased you got back to me. I appreciate the work you have done and
will be over the moon if you can expand on that.

With kind regards,

Andy

**Comment by aconz2** [comment]
Just pushed an update, can now select `n` or `all` versions. Please test and let me know

**Comment by aconz2** [comment]
Maybe? This sounds like it might be better suited to paid work and a different project, but you are welcome to create a new issue here discussing the features/goals you have in mind. A public discussion might be good if you knew of other users who had similar needs and they could chip in. You can email also me at my username at gmail and we can discuss privately if you prefer.
