### ISSUE TITLE
Subfolder Selection

### ISSUE THREAD

**Issue by getgray** [aconz2/Fusion360Exporter#13]
Glad to find this script, works better than the plugin I was using that failed on several things.  

I have several large projects with lots of subfolders.  Often I only do work in a subfolder but to "backup" using this script, I can only backup the entire project.  Having subfolder selection ability on the startup dialog would be great.

I now see there is some incremental functionality, suppose that will do meanwhile.

**Comment by aconz2** [comment]
Even with the incremental export, we do still visit all files in the root folder recursively. In the case that nothing new needs to be exported, no document will be opened and that is what takes the majority of time (from my recollection). However, whether by requirement or mistake (can't remember!) in reviewing the code, it looks like we always open a document if we are exporting sketches.

For UI to choose folders, the easiest is to just support one level of subfolder selection; I don't know or see a good way to do arbitrary nesting. Another option would be a text box that lets you enter some kind of matching pattern

Maybe it would be good to save different choices for preset settings

**Comment by aconz2** [comment]
Just pushed an update. It now supports one level folder, more info in readme. Hopefully you don't have deeply nested folders in mind

**Comment by getgray** [comment]
> Just pushed an update. It now supports one level folder, more info in readme. Hopefully you don't have deeply nested folders in mind
Thank you.  Appreciate that very much.  I have 2 layers deep (e.g. "robotics team\2022\", "robotics team\generic parts\" etc. but one layer deeper is appreciated.

**Comment by getgray** [comment]
Now if there was a way to rebuild them (import .f3d's back to F360) we'd be golden.  That would enable one to share exported folders where a recipient (in my case, a high school student who does not qualify for an edu license), could import them to their workspace.  I realize that's getting out of scope for the tool, and may not be possible, but asking in case I'm wrong.

**Comment by getgray** [comment]
Loaded it tonight.  F360 would not accept the new folder until I removed the Exporter.manifest file.  I saw that was the only thing different from the old version thus the crude attempt to fix.  That allowed me to add it to the scripts list.  So not sure if I'm missing anything.

**Comment by aconz2** [comment]
The .manifest file had a mistake and specified type "plugin" instead of "add-on" so it may have added, but moved to the plugins tab instead of scripts tab (it did for me). You might have to temporarily rename the Fusion360Exporter folder and reload fusion to convince it to remove the script since there's no way to do this (incredulously). Just pushed fixes

**Comment by getgray** [comment]
Loaded on a fresh PC and retried, worked without issue.  Thank you.
