### ISSUE TITLE
Support for Drawings (f2d) files

### ISSUE THREAD

**Issue by getgray** [aconz2/Fusion360Exporter#14]
Currently all my drawings are being skipped.    Sample log:

```
Visiting file CasterMountBlockDrawing v1 . f2d
file CasterMountBlockDrawing has extension f2d which is not currently handled, skipping
```

Can you add f2d to the export please?  Those are a PITA to create, be nice to have them backed up too.

**Comment by aconz2** [comment]
I'm not familiar with f2d, how do I create one to test with? From a quick google, it looks like there are some possible issues exporting them but I can look

**Comment by getgray** [comment]
Andrew, the f2d files are the drawing files.  You get to them via the Drawing enviroment (dropdown from design).  e.g.:

![image](https://github.com/aconz2/Fusion360Exporter/assets/20461271/b7966e12-cf95-4de3-828e-344da713d780)

**Comment by getgray** [comment]
![image](https://github.com/aconz2/Fusion360Exporter/assets/20461271/f630afa8-fd7e-460d-8a0c-9347087a4da0)

**Comment by getgray** [comment]
Thanks for trying.  I don't even see a way to do it manually.  F360 limitation.

**Comment by loglow** [comment]
> Thanks for trying. I don't even see a way to do it manually. F360 limitation.

@getgray,

If you "View Details on Web" for the drawing, you have the option there to download a "Fusion Archive" file (as well as a DWG or PDF). The Fusion Archive will be an `f3z` file that's actually a ZIP archive containing the `f2d` file you want as well as the `f3d` file that it references; both files will be named with what appear to be their ID hashes within the archive, not their human-readable names.

I don't know what practical options there are for using either the `f2d` or `f3z` files once they've been downloaded.
