### ISSUE TITLE
Preserving original date/time stamps

### ISSUE THREAD

**Issue by next-comp** [aconz2/Fusion360Exporter#17]
Is there any way to preserve original date/time stamps of exported projects?

**Comment by aconz2** [comment]
Yes I think so. The fusion `DataFile` has `dateCreated` and `dateModified` fields. Can use these to modify `export_file` function. `export_sketches` needs the file plumbed in so all sketches (if saved) would get their time set to the containing file. It doesn't look like there are per component or per sketch times so they'd all be taken from the file. For cross platform, setting modification time is the easiest. Windows does support setting creation time of a file I think but from a quick check there isn't an easy python way, only through win32. And would be easiest to only do this for new saves so it doesn't touch already exported files

**Comment by aconz2** [comment]
implemented in https://github.com/aconz2/Fusion360Exporter/commit/fd7345c5bad0b8ed177ab01aae0ccf7802b95cd2 there is an option to update already exported files, see readme for details
