### ISSUE TITLE
Project name/path is not sanitized

### ISSUE THREAD

**Issue by thomasa88** [aconz2/Fusion360Exporter#2]
The name path of a project needs to be sanitized. I have a project name with a slash (/) in it.
I hacked in `sanitize_filename()` at `new_ctx = ctx._replace(folder=ctx.folder / folder.name)` and it seems to be running OK for me now. Can't give a patch atm, as the export is running x).

edit. There might be an issue with folders inside projects as well (although I don't think I have any with odd characters).

**Comment by aconz2** [comment]
Good point. I thought of that briefly and naively thought no one would have that. 

Like this? https://github.com/aconz2/Fusion360Exporter/commit/804d2b10d6d2d56b48574a136f3852d45cf2fbbb

I just tried creating a test folder with a name like `Bad characters / ? *<>` inside a project and it wouldn't let me, saying the name was invalid. If you could provide a test case that would be great

**Comment by thomasa88** [comment]
> Like this? [804d2b1](https://github.com/aconz2/Fusion360Exporter/commit/804d2b10d6d2d56b48574a136f3852d45cf2fbbb)

Yes, exactly!

> I just tried creating a test folder with a name like `Bad characters / ? *<>` inside a project and it wouldn't let me, saying the name was invalid. If you could provide a test case that would be great

Same for me. Then it looks like it isn't a problem.
