### ISSUE TITLE
Versions are not always iterated in order / v9 missing

### ISSUE THREAD

**Issue by loglow** [aconz2/Fusion360Exporter#20]
Some of my files do not iterate their versions in descending order. These files were throwing errors when trying to archive previous versions. For example, instead of going 12, 11, 10, etc., a file might iterate its versions as 12, 8, 7, etc.

It seems like if there are more than 8 versions it does the latest version first but then jumps to v8, goes down some from there, and then jumps back up later. There's a sort of pattern, but it's sometimes odd.

I changed line 298 to `pass` and now it archives the various past versions instead of just doing only the latest one and then throwing a `not contiguous` exception and moving on.

Sometimes certain versions are missed. For example, on one run for a file with 24 versions, it downloaded everything except v1, v9, and v10. On the next run, it downloaded v1 and v10.

Finally, it seems like it will **never** download v9 for any file. I can open any v9 manually via the app and view them on the web but the export script never iterates them and they're never downloaded. This is the case for 8 different files that have more than 9 versions—all of them are missing their v9 in the export.

Any idea what's going on?

**Comment by loglow** [comment]
Okay, so I changed line 290 to the following by removing the `[1:]`

    versions = list(file.versions)

And now the v9 files are downloading properly.

I'm not sure why the list was being sliced like that, but that's what was causing my v9 files to be skipped.

**Comment by aconz2** [comment]
Thanks for reporting this

Hmm, so the comment (and what I recall) says that

> file.versions starts withe the current/latest version

and since I was assuming `file.versions` was in reverse sorted order (12, 11, 10, 9 ...) then for a current file of version 12, we slice off the current one (first of the list) and take the next `num_versions`.

Though I feel pretty smug that my paranoid check paid off!

If you wanted to do some testing I'd be curious what you get by adding something like this at the start of `def file_versions`
```python
log('FILE VERSION TEST', file.versionNumber, [x.versionNumber for x in file.versions])
```

**Comment by loglow** [comment]
Here's my log output for the `FILE VERSION TEST` lines only:

```
FILE VERSION TEST 1 [1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 4 [4, 3, 2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 4 [4, 3, 2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 6 [6, 5, 4, 3, 2, 1]
FILE VERSION TEST 6 [6, 5, 4, 3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 16 [9, 8, 7, 6, 5, 4, 3, 2, 16, 15, 14, 13, 12, 11, 10, 1]
FILE VERSION TEST 8 [8, 7, 6, 5, 4, 3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 6 [6, 5, 4, 3, 2, 1]
FILE VERSION TEST 10 [9, 8, 7, 6, 5, 4, 3, 2, 10, 1]
FILE VERSION TEST 11 [9, 8, 7, 6, 5, 4, 3, 2, 11, 10, 1]
FILE VERSION TEST 8 [8, 7, 6, 5, 4, 3, 2, 1]
FILE VERSION TEST 7 [7, 6, 5, 4, 3, 2, 1]
FILE VERSION TEST 4 [4, 3, 2, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 6 [6, 5, 4, 3, 2, 1]
FILE VERSION TEST 11 [9, 8, 7, 6, 5, 4, 3, 2, 11, 10, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 7 [7, 6, 5, 4, 3, 2, 1]
FILE VERSION TEST 8 [8, 7, 6, 5, 4, 3, 2, 1]
FILE VERSION TEST 6 [6, 5, 4, 3, 2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 4 [4, 3, 2, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 24 [9, 8, 7, 6, 5, 4, 3, 24, 23, 22, 21, 20, 2, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 6 [6, 5, 4, 3, 2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 4 [4, 3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 12 [9, 8, 7, 6, 5, 4, 3, 2, 12, 11, 10, 1]
FILE VERSION TEST 6 [6, 5, 4, 3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
FILE VERSION TEST 4 [4, 3, 2, 1]
FILE VERSION TEST 4 [4, 3, 2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 12 [9, 8, 7, 6, 5, 4, 3, 2, 12, 11, 10, 1]
FILE VERSION TEST 10 [9, 8, 7, 6, 5, 4, 3, 2, 10, 1]
FILE VERSION TEST 13 [9, 8, 7, 6, 5, 4, 3, 2, 13, 12, 11, 10, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 4 [4, 3, 2, 1]
FILE VERSION TEST 3 [3, 2, 1]
FILE VERSION TEST 1 [1]
FILE VERSION TEST 2 [2, 1]
FILE VERSION TEST 5 [5, 4, 3, 2, 1]
```

**Comment by aconz2** [comment]
Thank you! Lol they are in reverse sorted order, but by the ordering of the string of their version number! In other words

```python
x = [9, 8, 7, 6, 5, 4, 3, 24, 23, 22, 21, 20, 2, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 1]
x == sorted(x, key=str, reverse=True)
```

so I think the fix is to do something like:

```python
def file_versions(file: adsk.core.DataFile, num_versions):
    versions = sorted(file.versions, key=lambda x: x.versionNumber, reverse=True)
    if num_versions == -1:
        versions = list(versions)[1:]
    else:
        versions = list(versions)[1:num_versions+1]
    # ...
```

but not tested, will try it when I get a sec. Thanks for the testing

**Comment by loglow** [comment]
Ohhh that makes sense!

**Comment by aconz2** [comment]
fixed in https://github.com/aconz2/Fusion360Exporter/commit/f868aac937558b2639c331b056a1974c4fe87939 thanks again for reporting and helping on this
