### ISSUE TITLE
"Cloud solves are running the background"

### ISSUE THREAD

**Issue by thomasa88** [aconz2/Fusion360Exporter#3]
Got this popup while the exporter is running:
![image](https://user-images.githubusercontent.com/89997/93714948-4e78d880-fb66-11ea-8e10-0cf79bd51a8c.png)

Might possibly run automatically when the files are opened? (Export is still running, screenshot on another computer via remote desktop)
I have simulations in that file.

**Comment by aconz2** [comment]
Okay I will make a note on the readme about simulations. There's obviously a bunch of things I can't easily test for so thanks for the report
