### ISSUE TITLE
Error on electronics file

### ISSUE THREAD

**Issue by rafalmag** [aconz2/Fusion360Exporter#6]
I got following error when trying to do full export:
![error](https://user-images.githubusercontent.com/876630/93931849-9ee76600-fd1f-11ea-8991-8bd7a6ec9a96.PNG)

Most probably this happens due to unsupported electronics file. I think those kind of documents could be excluded from export.

The log:
```
Visiting folder Admin Project
Visiting file beam3 v1 . f3d
Opening `beam3`
filename `Beam3:1` contained bad chars, replacing by `Beam3 1`
Exporting sketch Sketch2 in Beam3 to C:\Users\Rafal\Documents\drukarka3d\moje\backups\Fusion360Export\Admin Project\beam3 v1\Beam3 1_1d0f16fd\Sketch2.dxf
Exporting sketch Sketch1 in Beam3 to C:\Users\Rafal\Documents\drukarka3d\moje\backups\Fusion360Export\Admin Project\beam3 v1\Beam3 1_1d0f16fd\Sketch1.dxf
Saved C:\Users\Rafal\Documents\drukarka3d\moje\backups\Fusion360Export\Admin Project\beam3_v1.f3d
Saved C:\Users\Rafal\Documents\drukarka3d\moje\backups\Fusion360Export\Admin Project\beam3_v1.step
Saved C:\Users\Rafal\Documents\drukarka3d\moje\backups\Fusion360Export\Admin Project\beam3_v1.igs
Closing beam3
...
Visiting file electornics_playground v1 . fbrd
Opening `electornics_playground`
```

PS: Great tool!

**Comment by aconz2** [comment]
Thanks for the report.

Should be fixed in https://github.com/aconz2/Fusion360Exporter/commit/bcabf0e9d7f38c53fbacf7ed60fbef2003cf2074 they will now get skipped.

Let me know if this fixes it for you. If it does, please close the issue

**Comment by rafalmag** [comment]
Cool! It successfully exported all projects now. The electronics objects were skipped as expected and the export continued with other object types. 🎉 
Closing 😀
