### ISSUE TITLE
Does not run on MacOSX Fusion360 due to python version mismatch

### ISSUE THREAD

**Issue by jmgurney** [aconz2/Fusion360Exporter#9]
The scripts appear to have been written against Python 3.7.  The version of Fusion360 I am running (2.0.3706) ships with Python 3.5.  I thought Fusion360 auto updated, but now I'm not sure, and finding what the latest version isn't easy, and I can't see where to d/l a new version.

A little more info from Fusion360:
```
import sys

sys.version
3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 08:49:46) \n[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```
I'm not sure where 3.5.3 is coming from, as I only have 3.4, 3.6, 3.7 installed locally.

Also, dataclasses was added in 3.7 (https://docs.python.org/3/library/dataclasses.html) which explains why it fails w/ Python 3.5.

I've made a number of changes to make it Python 3.5 compatible, but now I'm not sure how to handle NamedTuple:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jmg/github/Fusion360Exporter/foo.py", line 5, in test
    exec(data)
  File "<string>", line 41, in <module>
  File "/Users/jmg/Library/Application Support/Autodesk/webdeploy/production/1d09d44697aca8134bfd0a02c1326040d3faf96a/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.5/typing.py", line 1916, in __new__
    raise TypeError("Class syntax for NamedTuple is only supported"
TypeError: Class syntax for NamedTuple is only supported in Python 3.6+
```

I'm using this module:
```
def test():
	with open('/Users/jmg/github/Fusion360Exporter/Exporter.py') as fp:
		data = fp.read()

	exec(data)
```

To be able to get useful error messages from Fusion360.

**Comment by aconz2** [comment]
Fusion moved to 3.7.3 about 1 year ago https://forums.autodesk.com/t5/fusion-360-api-and-scripts/python-upgraded-to-3-7-3-and-spyder-replaced-by-vscode-coming/td-p/9017730/page/2 which corresponds to V.2.0.6503 https://www.autodesk.com/products/fusion-360/blog/september-23-2019-product-update-whats-new/ so I'm not sure what's going on

**Comment by jmgurney** [comment]
This is likely due to Autodesk giving me the latest supported version of Fusion360 for the version of MacOSX I run.  At least that's better than Apple, where they'll update your software to a version that is unsupported.
